/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apps;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import structures.Cell;
import structures.Map;

/**
 *
 * @author Jarisha
 */
public class GridPanel extends javax.swing.JPanel {     
     JButton[][] grid;
     Map m;
    /**
     * Creates new form Grid
     */
    public GridPanel() {
        initComponents();
         int width = 120;
                int length = 160;
                m = new Map();
                Cell[][] cells = m.getMap();
                jPanel1.setLayout(new GridLayout(width,length)); //set layout
                grid=new JButton[width][length]; //allocate the size of grid
                for(int x=0; x<width; x++){
                        for(int y=0; y<length; y++){
                                String str= cells[x][y].toString();
                                JButton b = new JButton();
                                b.setPreferredSize(new Dimension(10,10));
                                colorButton(b,cells[x][y]); //colors buttons according to cell type
                                b.addActionListener((ActionEvent e) -> {
                                    jLabel1.setText(str);//Shows cell information when cell is selected
                                });
                               
                                grid[x][y]=b; //creates new button     
                                jPanel1.add(grid[x][y]); //adds button to grid
                        }
                }
                               
    }
    public void setMap(Map map){
        m = map;
    }
    private void colorButton(JButton b, Cell c){
            if(c.getLocation().equals(m.getStartPoint())){
                b.setBackground(Color.yellow);
            }else if(c.getLocation().equals(m.getGoalPoint())){
                b.setBackground(Color.green);
            }else{
                switch(c.getCellType()){
                    case 0:
                        b.setBackground(Color.black);
                        break;
                    case 1:
                        b.setBackground(Color.white);
                        break;
                    case 2:
                        b.setBackground(Color.darkGray);
                        break;
                    case 3:
                        b.setBackground(Color.blue);
                        break;
                    case 4:
                        b.setBackground(Color.cyan);
                        break;
                    default:
                        b.setBackground(Color.white);
                        break;
                }
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Cell Info:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
